steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    
  # Step 2: Build the application with environment variables
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'VITE_SUPABASE_URL=${_SUPABASE_URL}'
      - 'VITE_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
    
  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ia-agendamentos:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ia-agendamentos:latest'
      - '.'
    
  # Step 4: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ia-agendamentos:$BUILD_ID'
    
  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ia-agendamentos'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ia-agendamentos:$BUILD_ID'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'VITE_SUPABASE_URL=${_SUPABASE_URL},VITE_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ia-agendamentos:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/ia-agendamentos:latest'

# Substitution variables (will be provided by the trigger)
substitutions:
  _SUPABASE_URL: 'https://ztfnnzclwvycpbapbbhb.supabase.co'
  _SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0Zm5uemNsd3Z5Y3BiYXBiYmhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNjM5NjIsImV4cCI6MjA4NDgzOTk2Mn0.j2J1E6xOQw_qKV4vY-FP0U_-ImmBqAWbzWGZ5hhcR1g'

# Timeout for the entire build
timeout: 1200s

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
